[package]
name = "jet"
version = "1.4.0"
edition = "2024"
description = "A fast, modern Java build tool inspired by Cargo and Bun."
license = "MIT OR Apache-2.0"
repository = "https://github.com/nktkt/jet"
homepage = "https://github.com/nktkt/jet"
readme = "README.md"
keywords = ["java", "build", "jvm", "maven", "gradle"]
categories = ["development-tools", "development-tools::build-utils"]
rust-version = "1.85"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml_edit = { version = "0.22", features = ["serde"] }
walkdir = "2"
which = "7"
ureq = { version = "2", default-features = false, features = ["tls"] }
quick-xml = "0.36"
sha2 = "0.10"
sha1 = "0.10"
hex = "0.4"
indicatif = "0.17"
dirs = "5"
zip = { version = "2", default-features = false, features = ["deflate"] }
glob = "0.3"
tar = "0.4"
flate2 = "1"
notify = "6"
signal-hook = "0.3"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
