//! `jet.lock` — TOML-formatted lockfile, mirrors Cargo.lock conventions.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::coord::Coord;
use crate::resolver::Resolution;

pub const LOCKFILE_NAME: &str = "jet.lock";
pub const LOCKFILE_VERSION: u32 = 1;

#[derive(Debug, Deserialize, Serialize)]
pub struct Lockfile {
    pub version: u32,
    pub root: RootPkg,
    #[serde(rename = "package", default)]
    pub packages: Vec<Package>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct RootPkg {
    pub name: String,
    pub version: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Package {
    pub name: String,
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub classifier: Option<String>,
    #[serde(rename = "type", default = "default_type")]
    pub ty: String,
    pub scope: String,
    /// Where the dep originates: `"main"` (from `[dependencies]`) or `"dev"`
    /// (only reachable from `[dev-dependencies]`). Defaults to `"main"` for
    /// 0.2 lockfiles missing the field.
    #[serde(default = "default_origin")]
    pub origin: String,
    pub url: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

fn default_origin() -> String {
    "main".into()
}

fn default_type() -> String {
    "jar".into()
}

impl Lockfile {
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(LOCKFILE_NAME);
        let text = fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        let lf: Lockfile = toml_edit::de::from_str(&text)
            .with_context(|| format!("parsing {}", path.display()))?;
        Ok(lf)
    }

    pub fn save(&self, root: &Path) -> Result<()> {
        let path = root.join(LOCKFILE_NAME);
        let body = toml_edit::ser::to_string_pretty(self)
            .context("serializing jet.lock")?;
        let header = format!(
            "# This file is automatically @generated by jet.\n\
             # It is not intended for manual editing.\n"
        );
        let tmp: PathBuf = path.with_extension("lock.tmp");
        fs::write(&tmp, format!("{header}{body}"))
            .with_context(|| format!("writing {}", tmp.display()))?;
        fs::rename(&tmp, &path)
            .with_context(|| format!("renaming {} → {}", tmp.display(), path.display()))?;
        Ok(())
    }

    pub fn from_resolution(
        manifest_name: &str,
        manifest_version: &str,
        resolution: &Resolution,
        repo_url: &str,
    ) -> Self {
        let mut packages: Vec<Package> = resolution
            .items
            .iter()
            .map(|r| Package {
                name: format!("{}:{}", r.coord.group, r.coord.artifact),
                version: r.coord.version.clone(),
                classifier: r.coord.classifier.clone(),
                ty: r.coord.ty.clone(),
                scope: r.scope.clone(),
                origin: r.origin.as_str().into(),
                url: r.coord.artifact_url(repo_url),
                sha256: None,
            })
            .collect();
        packages.sort_by(|a, b| {
            (a.name.as_str(), a.version.as_str(), a.classifier.as_deref())
                .cmp(&(b.name.as_str(), b.version.as_str(), b.classifier.as_deref()))
        });
        Lockfile {
            version: LOCKFILE_VERSION,
            root: RootPkg {
                name: manifest_name.into(),
                version: manifest_version.into(),
            },
            packages,
        }
    }

    pub fn coords(&self) -> Vec<Coord> {
        self.packages
            .iter()
            .filter_map(|p| {
                let (g, a) = p.name.split_once(':')?;
                Some(Coord {
                    group: g.into(),
                    artifact: a.into(),
                    version: p.version.clone(),
                    classifier: p.classifier.clone(),
                    ty: p.ty.clone(),
                })
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::resolver::{Resolved, resolve::Origin};

    #[test]
    fn round_trip() {
        let res = Resolution {
            items: vec![
                Resolved {
                    coord: "org.slf4j:slf4j-api:2.0.13".parse().unwrap(),
                    scope: "compile".into(),
                    origin: Origin::Main,
                },
                Resolved {
                    coord: "com.google.guava:guava:33.0.0-jre".parse().unwrap(),
                    scope: "compile".into(),
                    origin: Origin::Main,
                },
            ],
        };
        let lf = Lockfile::from_resolution("demo", "0.1.0", &res, "https://repo1.maven.org/maven2");
        assert_eq!(lf.version, LOCKFILE_VERSION);
        assert_eq!(lf.packages.len(), 2);
        assert_eq!(lf.packages[0].name, "com.google.guava:guava"); // sorted alpha

        let dir = tempfile::tempdir().unwrap();
        lf.save(dir.path()).unwrap();
        let txt = fs::read_to_string(dir.path().join(LOCKFILE_NAME)).unwrap();
        assert!(txt.contains("@generated by jet"));
        assert!(txt.contains("[root]"));

        let loaded = Lockfile::load(dir.path()).unwrap();
        assert_eq!(loaded.packages.len(), 2);
        assert_eq!(loaded.root.name, "demo");
    }
}
